# Docker Compose file for development
version: "3.4"

volumes:
  postgres:
  # root home dir in the postgres container to hold psql history
  postgreshome:
  # root home dir in the webserver container to hold ipython history
  webhome:

services:

  db:
    image: postgres:10.5
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgreshome:/root
    ports:
      - "15432:5432"

  webserver:
    build:
      context: ..
      dockerfile: Dockerfile
      target: acousticbrainz-dev
    environment:
      FLASK_ENV: development
    command: python manage.py runserver
    volumes:
      - ../:/code
      - webhome:/root
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - musicbrainz_database

  redis:
    image: redis:4.0-alpine

  musicbrainz_database:
    image: metabrainz/musicbrainz-test-database:schema-change-2017-q2
    volumes:
      - ../data/mbdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      MB_IMPORT_DUMPS: "true"
    ports:
      - "5430:5432"

  hl_extractor:
    build:
      context: ..
      dockerfile: Dockerfile
      target: acousticbrainz-dev
    command: python2 worker_manage.py hl_extractor
    volumes:
      - ../:/code
    depends_on:
      - db

  dataset_evaluator:
    build:
      context: ..
      dockerfile: Dockerfile
      target: acousticbrainz-dev
    command: python2 worker_manage.py dataset_evaluator
    volumes:
      - ../:/code
      - ../data/datasets:/data/datasets
      - ../data/files:/data/files
    depends_on:
      - db
