# Docker Compose file for development
version: "2"
services:

  db:
    image: postgres:9.5.4
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "15431:5432"

  acousticbrainz:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "8082:8080"
    depends_on:
      - db
      - redis

  redis:
    image: redis:4.0-alpine

  hl_extractor:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    depends_on:
      - db

  dataset_evaluator:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    depends_on:
      - db
