# Docker Compose file for development
version: "2"
services:

  db:
    image: postgres:9.5.4
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: acousticbrainz
      POSTGRES_PASSWORD: acousticbrainz
      POSTGRES_DB: acousticbrainz
    ports:
      - "15432:5432"

  webserver:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../:/code
      - ../data/app:/data
    ports:
      - "8080:8080"
    depends_on:
      - db
      - acousticbrainz_cache

  acousticbrainz_cache:
    image: redis:4.0-alpine

  hl_extractor:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.gaia
    depends_on:
      - db

  dataset_evaluator:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.gaia
    volumes:
      - ../:/eval
    depends_on:
      - db
