# Docker Compose file for test
version: "2"

volumes:
  postgres:

services:

  db:
    image: postgres:10.5
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "15431:5432"
    command: postgres -F

  acousticbrainz:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ..:/code:z
    depends_on:
      - db
      - redis

  redis:
    image: redis:4.0-alpine

  hl_extractor:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    depends_on:
      - db

  dataset_evaluator:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    depends_on:
      - db
